Upgrade erc20 to 0.14
CosmWasm/cosmwasm-examples pull request #124
Opened 2021-05-12 13:00 UTC by orkunkl

Related to #121

2021-05-13 06:28 UTC, maurolacy requested changes
Please address the comments, and I'll re-review, and finish reviewing tests.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +#[allow(clippy::unnecessary_wraps)]
You can avoid this by removing `write_allowance`'s return value, and modifying calls to it. (remove the subsequent question mark).

Also, probably out of scope here, but if you run clippy with `--all-targets`, there are a bunch of `clone()`s that can be removed.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +            .addr_canonicalize(address.as_str())
You can avoid this conversion entirely, and just use `address` as directly key.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +            .addr_canonicalize(owner.as_str())
Same here.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +            .addr_canonicalize(spender.as_str())
And here. Just remove all references to / uses of "canonical addresses".

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +    fn get_balance(api: &dyn Api, storage: &dyn Storage, address: &Addr) -> u128 {
Suggestion: Given that these are helper functions for tests, you can save a lot in conversions by just using `&str` for addresses.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/msg.rs
> +    pub address: Addr,
This should be of type `String`, as this struct is part of a message that can contain unvalidated addresses. When changing this, a lot of conversions (mostly in tests) will simplify / disappear.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +                    address: Addr::unchecked("addr0000".to_string()),
This and many others will simplify to `"addr0000".to_string()` when changing `InitialBalance::address`'s type to `String`.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +    fn mock_env_height(signer: &Addr, height: u64, time: u64) -> (Env, MessageInfo) {
Better to use `&str` for `signer` I guess.

2021-05-13 06:28 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +        env.block.time = Timestamp::from_nanos(time);
Not really relevant for these tests, but I think `from_seconds` makes more sense here.

2021-05-13 14:01 UTC, orkunkl commented on contracts/erc20/src/contract.rs
> +#[allow(clippy::unnecessary_wraps)]
I think making helpers return result could be a good practice, in case api changes and something that could return error inserted in write_allowance, no need to introduce huge changes

2021-05-13 14:02 UTC, orkunkl commented on contracts/erc20/src/contract.rs
> +    fn mock_env_height(signer: &Addr, height: u64, time: u64) -> (Env, MessageInfo) {
yeah introducs lots of change now.

2021-05-14 14:33 UTC, maurolacy commented
There's still an `addr_canonicalize()` in `src/contract.rs`, in the `token_balance()` fn that can be easily removed.

2021-05-17 07:16 UTC, orkunkl commented
I will disable integration tests because vm BackendApi is not updated

2021-05-19 08:32 UTC, maurolacy approved these changes
lgtm.

2021-05-19 08:32 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +pub fn read_u128(store: &ReadonlyPrefixedStorage, key: &Addr) -> Result<u128, ContractError> {
Just a detail: I would keep this function signature as it is, and convert to slice outside.

2021-05-19 08:32 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +                0 => Addr::unchecked("addr0000".to_string()), // contract instantiateializer
:-)
```suggestion
                0 => Addr::unchecked("addr0000".to_string()), // contract instantiation

2021-05-19 08:32 UTC, maurolacy commented on contracts/erc20/src/contract.rs
> +                address: address(4).to_string(), // only indices 1, 2, 3 are instantiateialized
```suggestion
                address: address(4).to_string(), // only indices 1, 2, 3 are initialized
```

2021-05-19 09:48 UTC, maurolacy commented
I've seen integration tests are failing (when ran manually). Let's either fix them, or delete them.

2021-05-24 06:47 UTC, merged