Upgrade voting to 0.14
CosmWasm/cosmwasm-examples pull request #125
Opened 2021-05-12 13:54 UTC by orkunkl

Related to https://github.com/CosmWasm/cosmwasm-examples/issues/121

2021-05-13 07:55 UTC, maurolacy requested changes
Will finish reviewing after requested changes.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/.cargo/config
> -integration-test = "test --test integration"
Why are you removing this?

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/msg.rs
> +    pub creator: Addr,
This should be a `String`, as it's part of a query response.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +        owner: deps.api.addr_canonicalize(&info.sender.as_str())?,
Modify `State` to change from `CanonicalAddr` to`Addr`, and use `info.sender` directly.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +    let sender_address_raw = deps.api.addr_canonicalize(&info.sender.as_str())?;
Use `info.sender` directly.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +    let sender_address_raw = deps.api.addr_canonicalize(&info.sender.as_str())?;
Idem.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> -                &sender_address_raw,
This is wrong. You should remove `contract_address_raw`, not `sender_addres_raw`. Wonder how the tests pass. Maybe it is a good idea to add a test that fails here.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +    let contract_address_raw = deps.api.addr_canonicalize(&env.contract.address.as_str())?;
This is not needed anymore (but see error below).

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +    let sender_address_raw = deps.api.addr_canonicalize(&info.sender.as_str())?;
Idem. Use `info.sender` directly.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +            attr("creator", deps.api.addr_humanize(&new_poll.creator)?),
Change `creator` to `Addr`, and use `to_string()` here.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +    let sender_address_raw = deps.api.addr_canonicalize(&info.sender.as_str())?;
Just use `info.sender`.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +    let sender_address_raw = deps.api.addr_canonicalize(&info.sender.as_str())?;
Idem.

2021-05-13 07:55 UTC, maurolacy commented on contracts/voting/src/contract.rs
>      to_address: &CanonicalAddr,
Should be `Addr`. Subsequent changes apply.

If you start by changing `CanonicalAddr` -> `Addr` in `state.rs`, and `HumanAddr` to `String` in `msg.rs` and `query.rs`, than all the changes follow more or less naturally.

2021-05-14 09:38 UTC, orkunkl commented on contracts/voting/.cargo/config
> -integration-test = "test --test integration"
Could not make it work with integration tests, also [vm::MockApi](https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/src/testing/mock.rs#L65) Is not updated.
Also the integration test are usually same as unit tests in cosmwasm/examples. This makes 2x time to maintain. Actually thinking to remove them?

2021-05-14 13:21 UTC, orkunkl commented on contracts/voting/src/contract.rs
> -                &sender_address_raw,
Actually my local tests were failing, and fixed it now

2021-05-14 14:19 UTC, maurolacy approved these changes
lgtm.

2021-05-14 14:19 UTC, maurolacy commented on contracts/voting/.cargo/config
> -integration-test = "test --test integration"
> Actually thinking to remove them?

OK with me.

2021-05-14 14:35 UTC, maurolacy commented on contracts/voting/src/contract.rs
> +    let key = deps.api.addr_canonicalize(&address.as_str())?;
This can be easily removed.

2021-05-14 14:37 UTC, maurolacy commented on contracts/voting/src/tests.rs
> +        let handle_res = execute(deps.as_mut(), env.clone(), info.clone(), msg.clone()).unwrap();
This `handle_res` and subsequent ones can be renamed for clarity.

2021-05-17 07:29 UTC, merged